FIXMEとTODOを変更
yunosuke924/rspec_app_exam pull request #1
Opened 2021-03-14 09:14 UTC by yunosuke924

<img width="938" alt="スクリーンショット 2021-03-14 18 11 04" src="https://user-images.githubusercontent.com/72934392/111063288-1210ae80-84f1-11eb-99d1-dda399270607.png">

2021-03-15 07:02 UTC, yuji91 requested changes
指摘事項の修正は、それぞれコミットの単位を分けるようにお願いします！

2021-03-15 07:02 UTC, yuji91 commented on spec/factories/tasks.rb
> +      status {2}
`2`だとどのような値か見て分からないので、enumに対応するシンボルを記載するようにしましょう。
```suggestion
      status { :done }
```

2021-03-15 07:02 UTC, yuji91 commented on spec/factories/tasks.rb
> +      completion_date {Time.current.yesterday}
細かいですがブレース（波括弧）の間はスペースを開けた方が見やすいですね。
```suggestion
      completion_date { Time.current.yesterday }
```

2021-03-15 07:02 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task){create(:task, project_id: project.id)}
Factoryに`association`を定義するとproject_idの指定は不要となります。
```suggestion
  let(:task){ create(:task) }
```

2021-03-15 07:02 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime("%-m/%d %-H:%M"))
`strftime`の引数を修正する直し方には問題点があります。NG例のPullRequstの指摘も確認してください。

2021-03-15 07:02 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content "title: #{task.title}"
この指定方法でも大丈夫ですが「pageオブジェクト全体を確認している」点を変更した方が良いですね。
ヒントはこのテストコード中の書き方にあります。
またデバッグで`page.body`で出力される値も確認してみてください。

2021-03-15 09:41 UTC, yunosuke924 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content "title: #{task.title}"
Fix: expectのスコープを変更。伴ってエラー発生。（e4d0293） にて、エラーが発生し、解消できません。
debuggerを差し込んで確認をすると、Taskのcountは0と表示されるにも関わらず、テスト結果は１を示します。ローカル変数taskを確認すると、確かに常に中身があります。task.destroyでも消せません。
また、1番の謎は、debuggerを差し込むと、テストがパスすることです。デバッグツールを使うか使わないかで結果が変わってしまうと、ツールの意味をなさないと思ってしまうのですが、何が起きているのでしょうか・・・？
<img width="678" alt="スクリーンショット 2021-03-15 17 58 30" src="https://user-images.githubusercontent.com/72934392/111133476-ec051000-85bd-11eb-8fec-1c1bac8f1f8a.png">
<img width="1363" alt="スクリーンショット 2021-03-15 18 07 35" src="https://user-images.githubusercontent.com/72934392/111133518-f7583b80-85bd-11eb-8437-fc9c266931a4.png">

2021-03-15 09:43 UTC, yunosuke924 commented on spec/factories/tasks.rb
> +      status {2}
cd07edb　statusの値をenumを使用した値　（:done）に変更しました。

2021-03-15 09:44 UTC, yunosuke924 commented on spec/factories/tasks.rb
> +      completion_date {Time.current.yesterday}
4251094 ブレースの間に半角スペースを入れて見やすくしました。

2021-03-15 09:45 UTC, yunosuke924 commented on spec/system/task_spec.rb
> +  let(:task){create(:task, project_id: project.id)}
fed8518 Factoryの定義で、taskにassociationの設定を付与し、project_idの指定を外しました。

2021-03-15 09:48 UTC, yunosuke924 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime("%-m/%d %-H:%M"))
02b8978 ApplicationHelperに定義したメソッドを使えるようにするために、rails_helper.rbに設定を追記し、該当のコードを修正しました。

2021-03-15 10:38 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content "title: #{task.title}"
> debuggerを差し込むと、テストがパスすること

これは仕様なのであまり気にしなくて大丈夫です。そもそもデバッグ用のコードを残したままテストコードをPushすることはまずありません。ローカル環境で情報の確認が済んだら、デバッグ用のコードは削除することになります。

> 伴ってテストが通らなくなり、解消できません。

こちらはどの部分のテストケースが解消できないのかが分かりませんでした。
またコミットを確認したところ、変更箇所が２つありました。
どちらも問題なのか、どちらかだけが問題なのかが分かるように、コミットの単位は分けた方が良いです。

2021-03-15 11:56 UTC, yunosuke924 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content "title: #{task.title}"
expectの引数のタイポと、CSSタグをfindを使って指定していなかったことが原因のようでした。引数を`expect(find('.task_list'))`と記載したら、テストはきちんとパスをしました。
最終的なコードの状態としては、こちらで問題ないでしょうか？

2021-03-16 06:38 UTC, yuji91 approved these changes
修正確認したのでLGTMです！
コメントした1点は細かい部分なので、直さなくてもOKです！

2021-03-16 06:38 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task){create(:task)}
スペースを開けた方が見やすくなりますね
```suggestion
  let(:project) { create(:project) }
  let(:task) { create(:task) }
```

2021-06-05 16:04 UTC, closed without merging